_schema-version: "3.3"
ID: employee-management
version: 1.0.0

parameters:
  enable-parallel-deployments: true

build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install
        - npx cds build --production

modules:

  - name: employee-srv
    type: nodejs
    path: gen/srv

    parameters:
      memory: 512M
      disk-quota: 512M

    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}

    requires:
      - name: employee-db
      - name: employee-xsuaa
      - name: employee-destination

    build-parameters:
      builder: npm-ci

  - name: employee-db-deployer
    type: hdb

    path: gen/db

    requires:
      - name: employee-db

resources:

  - name: employee-db
    type: com.sap.xs.hdi-container

    parameters:
      service: hana
      service-plan: hdi-shared

  - name: employee-xsuaa
    type: org.cloudfoundry.managed-service

    parameters:
      service: xsuaa
      service-plan: application
      path: xs-security.json

  - name: employee-destination
    type: org.cloudfoundry.managed-service

    parameters:
      service: destination
      service-plan: lite
